trigger:
  - azure-pipelines
  - master

jobs:
  - job: Ubuntu_unit_test

    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - task: UsePythonVersion@0
        displayName: 'Get Python version $(python.version)' 
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'
        
      - script: python -m pip install --upgrade pip
        displayName: "Upgrade pip"

      - script: |
          # commands run within the step
          pip install -r requirements.txt
        displayName: 'Install dependencies'

      - script: |
          python -m pip install pylint --quiet
          pylint boston/*.py
          pylint iris/*.py
        displayName: 'Run lint tests'