trigger:
  - azure-pipelines
  - master

jobs:
  - job: Ubuntu_unit_test

    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - script: |
          pip install -U pip
          pip install -r requirements.txt
        displayName: 'Install things'

      - script: |
          python -m pip install pylint --quiet
          pylint boston/*.py
          pylint iris/*.py
        dispayName: 'Run lint tests'